[[language]]
name = "deno-javascript"
language-servers = [ "deno-lsp" ]
roots = [ "deno.json" ]
scope = "source.js"
file-types = [ "js" ]

[[language]]
name = "deno-typescript"
language-servers = [ "deno-lsp" ]
roots = [ "deno.json" ]
scope = "source.ts"
file-types = [ "ts" ]

[[language]]
name = "deno-tsx"
language-servers = [ "deno-lsp" ]
roots = [ "deno.json" ]
scope = "source.tsx"
file-types = [ "tsx" ]

[language-server.deno-lsp]
command = "deno"
args = [ "lsp" ]
config = { enable = true, importMap = "deno.json", provideFormatter = true }
